language: scala
scala:
  - 2.11.7
env:
  - ACTIVATOR_VERSION=2.5.8
script:
  - sbt test
jdk:
  - oraclejdk8
mysql:
  - 5.7.15
services:
  - mysql
before_script: 
  - mysql -u root -e "CREATE DATABASE mydatabase;"

