language: scala
scala:
  - 2.11.7
script:
  - "cd $TRAVIS_BUILD_DIR/code"
  - "sbt ++$TRAVIS_SCALA_VERSION test"
  - "sbt ++$TRAVIS_SCALA_VERSION publish-local"
jdk:
  - oraclejdk8
services:
  - mysql
before_script:
- mysql -u root -e 'CREATE DATABASE users;'
- mysql -u root -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root';"
- mysql -u root -e "GRANT ALL ON users.* TO 'root'@'localhost';"
