language: scala
scala:
  - 2.11.7
env:
  - ACTIVATOR_VERSION=2.5.8
script:
  - sbt test
jdk:
  - oraclejdk8
dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
before_script: 
  - mysql -u root -e "CREATE DATABASE mydatabase;"

