language: scala
scala:
  - 2.11.7
env:
  - ACTIVATOR_VERSION=2.5.8
script:
  - "cd $TRAVIS_BUILD_DIR/code"
  - "sbt ++$TRAVIS_SCALA_VERSION test"
  - "sbt ++$TRAVIS_SCALA_VERSION publish-local"
jdk:
  - oraclejdk8
services:
  - mysql
before_script:
- mysql -u root -e "CREATE DATABASE users;"
